version: '3.6'

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  portainer_data:

services:
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - label-enable=true
    - interval=30

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    environment:
    - VIRTUAL_PROTO=https
    - VIRTUAL_PORT=443
    labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    - com.centurylinklabs.watchtower.enable='false'

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx:/etc/docker-gen/templates:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    - com.centurylinklabs.watchtower.enable='false'
    depends_on:
    - nginx
    - nginx-letsencrypt

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx
    - NGINX_PROXY_CONTAINER=nginx-gen
    labels:
    - com.centurylinklabs.watchtower.enable='false'

  portainer:
    container_name: llt.portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "portainer_data:/data"
    - "nginx_certs:/certs"
    environment:
    - VIRTUAL_HOST=portainer.${DOMAIN}
    - LETSENCRYPT_HOST=portainer.${DOMAIN}
    - LETSENCRYPT_EMAIL=${USER_EMAIL}
    - ssl="true"
    - sslcert=/certs/portainer.${DOMAIN}.crt
    - sslkey=/certs/portainer.${DOMAIN}.key
    labels:
    - com.centurylinklabs.watchtower.enable='true'
