version: '3.6'

services:
  lowlandtech_customer:
    hostname: customer.${DOMAIN}
    container_name: lowlandtech_customer
    restart: always
    expose:
    - 4200
    image: lowlandtech/customer:latest
    build:
      context: .
